### ISSUE TITLE
iOS radio button text not rendering

### ISSUE THREAD

**Issue by JustinJohnWilliams** [kirtisagar/XamarinFormsRadioButtonXAML#3]
I brought in your source to add RadioButtons to my application. It works perfectly well with Android, however, I cannot get the text to show correctly in iOS. I am not implementing a WinPhone solution.

I created a sample GitHub project to repro, please see it at: 

https://github.com/JustinJohnWilliams/CustomRadioButtons

I have screenshots attached in there as well.

**Comment by toverux** [comment]
I had the same problem.
I noticed that that was because the text color was not set, the text was white on the default white background.

You can either use `CustomRadioButton.TextColor` (provided in this example, but not implemented in the Android renderer), or do it like me and call `radioButton.SetTitleColor(UIColor.Black, UIControlState.Normal);` in the Control initialization, into the iOS renderer, to give it a default color.

**Comment by kirtisagar** [comment]
please find the latest code is part of XLabs: 
https://github.com/XLabs/Xamarin-Forms-Labs
